name: Build

on: [pull_request, push, repository_dispatch]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Checkout adafruit/ci-arduino
        uses: actions/checkout@v3
        with:
          repository: adafruit/ci-arduino
          path: ci

      - name: pre-install
        run: bash ci/actions_install.sh

      # clang is already run as part of pre-commit
      # - name: clang
      # run: python3 ci/run-clang-format.py -r src/arduino

#      - name: doxygen
#        env:
#          GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
#          PRETTYNAME : "Adafruit Faux86 Library"
#        run: bash ci/doxy_gen_and_deploy.sh

  build:
    strategy:
      fail-fast: false
      matrix:
        arduino-platform:
          # change to metro esp32s3 later on when available
          - 'qualia_s3_rgb666'

    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Checkout adafruit/ci-arduino
      uses: actions/checkout@v3
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    - name: test platforms
      run: python3 ci/build_platform.py ${{ matrix.arduino-platform }}
